version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: db-chinomarket
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: 'chinomarket'
      POSTGRES_USER: 'chinomarketserver'
      POSTGRES_PASSWORD: 'chinomarket2025'
    ports:
      - '5435:5432'

  msp-registry-server:
    image: msp-registry-server:latest
    build: ./registry-server
    container_name: registry-server
    restart: always
    ports:
      - "8761:8761"

  msp-config-server:
    image: msp-config-server:latest
    build: ./config-server
    container_name: config-server
    restart: always
    ports:
      - "7777:7777"
    depends_on:
      - msp-registry-server
    environment:
      EUREKA_URL: http://msp-registry-server:8761/eureka/

  msp-marketchino:
    image: msp-marketchino-master:latest
    build: ./MarketChino-master
    container_name: marketchino
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - msp-config-server
      - db
    environment:
      EUREKA_URL: http://msp-registry-server:8761/eureka/
      CONFIG_SERVER: http://msp-config-server:7777


  
