spring:
  datasource:
    username: chinomarketserver
    password: chinomarket2025
    url: jdbc:postgresql://localhost:5433/chinomarket
    hikari:
     maximum-pool-size: '5'
     connection-timeout: '20000'


  application:
    name: chinomarket-crud

  profiles:
    #prod     #profile in production
    #default  #profile in dev
    default: default

  config:
    import: 'optional:configserver:http://localhost:7777'
    #import: 'optional:configserver:${CONFIG_SERVER_HOST}'

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  servlet:
    context-path: /chinomarket-crud
  port: "8081"

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/