spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Benroj0/microservice-config-market.git
          default-label: master
          clone-on-start: true
          #usamos user and password when repository is private en github
          username: Benroj0
          #use variable entorno
          password: ${GIT_TOKEN}
server:
  port: 7777

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      #static no docker
      #defaultZone: http://localhost:8761/eureka/
      #dynamic with build docker
      defaultZone: ${EUREKA_URL}